# Generated by Django 6.0.7 on 2026-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('data_da_despesa', models.IntegerField()),
            ],
        ),
    ]
